[package]
name = "gossip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = { version = "*", features = ["mdns"] }
futures = "*"
async-std = "*"
eframe = "*"
